exchange_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('swap.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swap/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, MyOfferView, MyOffersJSONExportView, BoughtOffersJSONExportView, BoughtOfferJSONExportView, BoughtOfferView,  BuyOfferView, BoughtOffers, OfferView, AddOfferView, Search, OfferJSONExportView, ImportOfferFromJSONView, OffersJSONExportView, Login, UserLogout, Register, UserOffers, EditOfferView, DeleteOfferView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('add_offer/', AddOfferView.as_view(), name='add_offer'),
    path('buy_offer/<str:slug>/', BuyOfferView.as_view(), name='buy_offer'),
    path('edit_offer/<str:slug>/', EditOfferView.as_view(), name='edit_offer'),
    path('delete_offer/<str:slug>/', DeleteOfferView.as_view(), name='delete_offer'),
    path('import_offer_from_json/', ImportOfferFromJSONView.as_view(), name='import_offer_from_json'),
    path('search/', Search.as_view(), name='search'),
    path('my_offers/', UserOffers.as_view(), name='user_offers'),
    path('my_bought_offers/', BoughtOffers.as_view(), name='my_bought_offers'),
    path('export_offers_to_json', OffersJSONExportView.as_view(), name='export_offers_to_json'),
    path('export_my_offers_to_json', MyOffersJSONExportView.as_view(), name='export_my_offers_to_json'),
    path('export_bought_offers_to_json', BoughtOffersJSONExportView.as_view(), name='export_bought_offers_to_json'),
    path('offer/<str:slug>/', OfferView.as_view(), name='offer'),
    path('bought_offer/<str:slug>/', BoughtOfferView.as_view(), name='bought_offer'),
    path('my_offer/<str:slug>/', MyOfferView.as_view(), name='my_offer'),
    path('offer/<str:slug>/export', OfferJSONExportView.as_view(), name='export_offer'),
    path('bought_offer/<str:slug>/export', BoughtOfferJSONExportView.as_view(), name='bought_export_offer'),
    path('login', Login.as_view(), name='login'),
    path('logout', UserLogout.as_view(), name='logout'),
    path('register', Register.as_view(), name='register'),
]

swap/models.py
from django.db import models

# Create your models here.

swap/forms.py
from django import forms


class OfferForm(forms.Form):

    CATEGORY_CHOICES = [
        ('Мебель', 'Мебель'),
        ('Одежда', 'Одежда'),
        ('Бытовая техника', 'Бытовая техника'),
        ('Посуда', 'Посуда'),
        ('Продукты', 'Продукты'),
    ]

    STATE_CHOICES = [
        ('Новое', 'Новое'),
        ('Хорошее', 'Хорошее'),
        ('Среднее', 'Среднее'),
        ('Требует ремонта', 'Требует ремонта'),

    ]

    title = forms.CharField(label="Название", widget=forms.TextInput(attrs={"class": "form-control"}))
    description = forms.CharField(label="Описание", widget=forms.Textarea(attrs={"class": "form-control"}))
    photo = forms.ImageField()
    weight = forms.IntegerField(label="Вес", widget=forms.NumberInput(attrs={"class": "form-control"}))
    size = forms.IntegerField(label="Размер", widget=forms.NumberInput(attrs={"class": "form-control"}))
    category = forms.ChoiceField(label="Категория", choices=CATEGORY_CHOICES, widget=forms.Select(attrs={"class": "form-control"}))
    state = forms.ChoiceField(label="Состояние", choices=STATE_CHOICES, widget=forms.Select(attrs={"class": "form-control"}))
    city = forms.CharField(label="Город", widget=forms.TextInput(attrs={"class": "form-control"}))
    price = forms.IntegerField(label="Цена", widget=forms.NumberInput(attrs={"class": "form-control"}))

class ImportOfferFromJSONForm(forms.Form):
    file = forms.FileField(label='Файл')
    
class LoginForm(forms.Form):
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={"class": "form-control"}))
    password = forms.CharField(label="Пороль", widget=forms.PasswordInput(attrs={"class": "form-control"}))


class RegisterForm(forms.Form):
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={"class": "form-control"}))
    password = forms.CharField(label="Пороль", widget=forms.PasswordInput(attrs={"class": "form-control"}))
    full_name = forms.CharField(label="Имя пользователя", widget=forms.TextInput(attrs={"class": "form-control"}))

class EditOfferForm(forms.Form):

    CATEGORY_CHOICES = [
        ('Мебель', 'Мебель'),
        ('Одежда', 'Одежда'),
        ('Бытовая техника', 'Бытовая техника'),
        ('Посуда', 'Посуда'),
        ('Продукты', 'Продукты'),
    ]

    STATE_CHOICES = [
        ('Новое', 'Новое'),
        ('Хорошее', 'Хорошее'),
        ('Среднее', 'Среднее'),
        ('Требует ремонта', 'Требует ремонта'),

    ]

    title = forms.CharField(label="Название", widget=forms.TextInput(attrs={"class": "form-control"}))
    description = forms.CharField(label="Описание", widget=forms.Textarea(attrs={"class": "form-control"}))
    photo = forms.ImageField(required=False)
    weight = forms.IntegerField(label="Вес", widget=forms.NumberInput(attrs={"class": "form-control"}))
    size = forms.IntegerField(label="Размер", widget=forms.NumberInput(attrs={"class": "form-control"}))
    category = forms.ChoiceField(label="Категория", choices=CATEGORY_CHOICES, widget=forms.Select(attrs={"class": "form-control"}))
    state = forms.ChoiceField(label="Состояние", choices=STATE_CHOICES, widget=forms.Select(attrs={"class": "form-control"}))
    city = forms.CharField(label="Город", widget=forms.TextInput(attrs={"class": "form-control"}))
    price = forms.IntegerField(label="Цена", widget=forms.NumberInput(attrs={"class": "form-control"}))

swap/views.py
import os
from pathlib import Path
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
import pymongo
import re
from bson.json_util import dumps, loads
import json
from bson.objectid import ObjectId
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, FormView, TemplateView, View, UpdateView, DeleteView
from django.views.generic.edit import DeletionMixin
from pymongo import TEXT
import datetime
from .forms import ImportOfferFromJSONForm, OfferForm, LoginForm, RegisterForm, EditOfferForm
from django.core.paginator import Paginator

BASE_DIR = Path(__file__).resolve().parent.parent

# Подключение к MongoClient
client = pymongo.MongoClient('mongo', 27017, username='admin', password='admin')
# Получаем базу данных
dbname = client['swap_db']
# Получаем коллекцию(аналог таблицы)
offers_collection = dbname['swap_collection']
# Таблица купленного
selled_offers_collection = dbname['selled_collection']

offers = [
  { "title": "Some title 1",
        "description": "Some description abc",
        "weight": "45",
        "size": "30",
        "category": "Мебель",
        "state": "Новое",
        "city": "Moscow",
        "price": "450",
        "created_at": "16-12-2022 20:18",
        "owner": "Bob",
        },
    {"title": "Some title 2",
     "description": "Some description zxc",
     "weight": "35",
     "size": "5",
     "category": "Мебель",
     "state": "Хорошее",
     "city": "Taganrog",
     "price": "120",
     "created_at": "16-12-2022 20:18",
     "owner": "Bob",
     },
    {"title": "Some title 3",
     "description": "Some description qwe",
     "weight": "77",
     "size": "51",
     "category": "Мебель",
     "state": "Новое",
     "city": "Moscow",
     "price": "150",
     "created_at": "16-12-2022 20:18",
     "owner": "Bob",
     },
    {"title": "Some title 4",
     "description": "Some description fgh",
     "weight": "70",
     "size": "51",
     "category": "Одежда",
     "state": "Новое",
     "city": "Belgorod",
     "price": "250",
     "created_at": "16-12-2022 20:18",
     "owner": "Bob",
     },
    {"title": "Some title 5",
     "description": "Some description opl",
     "weight": "71",
     "size": "51",
     "category": "Одежда",
     "state": "Хорошее",
     "city": "Belomorsk",
     "price": "250",
     "created_at": "16-12-2022 20:18",
     "owner": "Bob",
     },
    {"title": "Some title 6",
     "description": "Some description mhg",
     "weight": "73",
     "size": "51",
     "category": "Одежда",
     "state": "Среднее",
     "city": "Sarta",
     "price": "1590",
     "created_at": "16-12-2022 20:18",
     "owner": "Bob",
     },
    {"title": "Some title 7",
     "description": "Some description nmg",
     "weight": "55",
     "size": "30",
     "category": "Мебель",
     "state": "Новое",
     "city": "Moscow",
     "price": "450",
     "created_at": "16-12-2022 20:18",
     "owner": "Bob",
     },
]

users_collection = dbname['users_collection']
users_collection.create_index([('email', pymongo.ASCENDING)], unique=True)

offers_collection.insert_many(offers)

class HomeView(TemplateView):
    template_name = "home.html"
    def get_context_data(self, ** kwargs):
        context = super().get_context_data(**kwargs)
        dbname = client['swap_db']
        collection = dbname['swap_collection']
        context["offers"] = collection.find()
        offers = list(collection.find())
        paginator = Paginator(offers, 9)
        page_number = self.request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        return context


class OfferView(TemplateView):
    template_name = "offer.html"

    def get_context_data(self, ** kwargs):
        context = super().get_context_data(**kwargs)
        context["offer"] = offers_collection.find_one({"_id": ObjectId(self.kwargs.get("slug"))})
        # context["can_write"] = self.request.user.username == context["offer"]
        context["id"] = self.kwargs.get("slug")
        return context


class Search(TemplateView):
    template_name = "search.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        offers_collection.create_index([('title', TEXT)], default_language='english')
        print(self.request.GET.get('category'))
        if self.request.GET.get('category') == "Категория" and self.request.GET.get('state') == "Состояние":
            offers = offers_collection.find({
               "$and": [{"title": {"$regex": f".*{self.request.GET.get('title')}.*", "$options": 'i'}},
                       {"description": {"$regex": f".*{self.request.GET.get('description')}.*", "$options": 'i'}},
                        {"weight": {"$regex": f".*{self.request.GET.get('weight')}.*", "$options": 'i'}},
                        {"size": {"$regex": f".*{self.request.GET.get('size')}.*", "$options": 'i'}},
                        {"price": {"$regex": f".*{self.request.GET.get('price')}.*", "$options": 'i'}},
                       {"city": {"$regex": f".*{self.request.GET.get('city')}.*", "$options": 'i'}}]
            })
        elif self.request.GET.get('state') == "Состояние":
            offers = offers_collection.find({
                "$and": [{"title": {"$regex": f".*{self.request.GET.get('title')}.*", "$options": 'i'},
                         'category': f"{self.request.GET.get('category')}"},
                        {"description": {"$regex": f".*{self.request.GET.get('description')}.*", "$options": 'i'},
                         'category': f"{self.request.GET.get('category')}"},
                        {"weight": {"$regex": f".*{self.request.GET.get('weight')}.*", "$options": 'i'},
                         'category': f"{self.request.GET.get('category')}"},
                        {"size": {"$regex": f".*{self.request.GET.get('size')}.*", "$options": 'i'},
                         'category': f"{self.request.GET.get('category')}"},
                        {"price": {"$regex": f".*{self.request.GET.get('price')}.*", "$options": 'i'},
                         'category': f"{self.request.GET.get('category')}"},
                        {"city": {"$regex": f".*{self.request.GET.get('city')}.*", "$options": 'i'},
                         'category': f"{self.request.GET.get('category')}"}]})
        elif self.request.GET.get('category') == "Категория":
            offers = offers_collection.find({
                "$and": [{"title": {"$regex": f".*{self.request.GET.get('title')}.*", "$options": 'i'},
                         'state': f"{self.request.GET.get('state')}"},
                        {"description": {"$regex": f".*{self.request.GET.get('description')}.*", "$options": 'i'},
                         'state': f"{self.request.GET.get('state')}"},
                        {"weight": {"$regex": f".*{self.request.GET.get('weight')}.*", "$options": 'i'},
                         'state': f"{self.request.GET.get('state')}"},
                        {"size": {"$regex": f".*{self.request.GET.get('size')}.*", "$options": 'i'},
                         'state': f"{self.request.GET.get('state')}"},
                        {"price": {"$regex": f".*{self.request.GET.get('price')}.*", "$options": 'i'},
                         'state': f"{self.request.GET.get('state')}"},
                        {"city": {"$regex": f".*{self.request.GET.get('city')}.*", "$options": 'i'},
                         'state': f"{self.request.GET.get('state')}"}]})
        else:
            offers = offers_collection.find({
                "$and": [{"title": {"$regex": f".*{self.request.GET.get('title')}.*", "$options": 'i'},
                         'state': f"{self.request.GET.get('state')}",
                         'category': f"{self.request.GET.get('category')}"},
                        {"description": {"$regex": f".*{self.request.GET.get('description')}.*", "$options": 'i'},
                         'state': f"{self.request.GET.get('state')}",
                         'category': f"{self.request.GET.get('category')}"},
                        {"weight": {"$regex": f".*{self.request.GET.get('weight')}.*", "$options": 'i'},
                         'state': f"{self.request.GET.get('state')}",
                         'category': f"{self.request.GET.get('category')}"},
                        {"size": {"$regex": f".*{self.request.GET.get('size')}.*", "$options": 'i'},
                         'state': f"{self.request.GET.get('state')}",
                         'category': f"{self.request.GET.get('category')}"},
                        {"price": {"$regex": f".*{self.request.GET.get('price')}.*", "$options": 'i'},
                         'state': f"{self.request.GET.get('state')}",
                         'category': f"{self.request.GET.get('category')}"},
                        {"city": {"$regex": f".*{self.request.GET.get('city')}.*", "$options": 'i'},
                         'state': f"{self.request.GET.get('state')}",
                         'category': f"{self.request.GET.get('category')}"}]})

        
        paginator = Paginator(list(offers), 9)
        page_number = self.request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
        context["page_obj"] = page_obj
        context["text"] = self.request.GET.get('category')
        context["full_path"] = re.sub(r"&+page=\d*", "", self.request.get_full_path())
        return context


class AddOfferView(FormView):
    template_name = "add_offer.html"
    form_class = OfferForm

    def form_valid(self, form):
        img = form.cleaned_data.get('photo')
        path = default_storage.save('tmp/somename.png', ContentFile(img.read()))

swap/templates/add_offer.html
{% extends 'base.html'%}
{% load static %}

{% block title %}
Add offer
{% endblock %}

{% block content %}
<section class="pb-3">
    <div class="container-fluid ">
        <div class="row ">
            <div class="col-lg-2"></div>
            <div class="col-lg-8 col-md-12">
              <form enctype="multipart/form-data" method="post">
                  {% csrf_token %}
                  {{ form.non_form_errors }}
                  {{form.as_p}}
                  <div class="mt-3 mb-5">
                      <button type="submit" class="px-5 btn" style="color: rgb(191, 120, 163); border-style: solid; border-width: 0.5px; border-color: rgb(191, 120, 163);">Добавить</button>
                  </div>
              </form>
              <button type="button" class="px-5 btn" style="color: rgb(191, 120, 163); border-style: solid; border-width: 0.5px; border-color: rgb(191, 120, 163);" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Import from JSON
              </button>
              <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Импорт</h5>
                      <button type="button" class="btn-close reg-button" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form enctype="multipart/form-data" action="{% url 'import_offer_from_json' %}" method="post">
                        {% csrf_token %}
                        <input name="file" type="file">
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn reg-button" data-bs-dismiss="modal">Закрыть</button>
                      <button type="submit" class="btn reg-button">Импортировать</button>
                    </div>
                </form>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>
</section>
{% endblock %}

swap/templates/bought_offer.html
{% extends 'base.html'%}
{% load static %}
{% load get_id_tag %}

{% block title %}
{{offer.title}}
{% endblock %}

{% block content %}
<section class="pb-3 hello">
  <div class="container-fluid ">
    <div class="row p-3">
      <div class="col-lg-5 m-4">
        {% if offer.photo %}
        <img src="{{offer.photo}}" class="card-img-top" alt="card text">
        {% else %}
        <img src="{% static '/icon/offer_default.jpg' %}" class="card-img-top" alt="card text">
        {% endif %}
      </div>
      <div class="col-lg-6 col-md-12 mt-4">
        <div class="row my-3">
          <div class="col">
            <div class="container-fluid">
              <div class="row ">
                <div class="col-lg-12 col-md-12">
                  <div class="row">
                    <p>Описание: {{offer.description}}</p>
                    <p>Вес: {{offer.weight}}</p>
                    <p>Размер: {{offer.size}}</p>
                    <p>Город: {{offer.city}}</p>
                    <p>Категория: {{offer.category}}</p>
                    <p>Состояние: {{offer.state}}</p>
                    <p>Стоимость: {{offer.price}}</p>
                    <p>Дата создания: {{offer.created_at}}</p>
                    <p>Приобретено у {{offer.owner}}</p>
                    <p>Находиться в пути</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-12 mx-4">
        <form action="{% url 'bought_export_offer' id %}" method="GET">
          <button type="submit" class="px-5 btn" style="color: rgb(191, 120, 163); border-style: solid; border-width: 0.5px; border-color: rgb(191, 120, 163);" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Export to JSON
          </button>
        </form>
      </div>


    </div> 
  </div>

</section>
{% endblock %}

swap/templates/bought_offers.html
{% extends 'base.html'%}
{% load get_id_tag %}
{% load static %}

{% block title %}
Swap
{% endblock %}

{% block content %}

<section class="pb-3">
    <div class="container-fluid ">
        <div class="row ">
            <div class="col-lg-2"></div>
            <div class="col-lg-8 col-md-12">

                <div class="row">
                    {% for offer in offers %}
                    <div class="col-lg-4 col-md-6 mt-4">
                        <div class="card">
                            {% if offer.photo %}
                            <a href="{% url 'bought_offer' offer|mongo_id %}"><img src="{{offer.photo}}" class="card-img-top" alt="card text"> </a>
                            {% else %}
                            <a href="{% url 'bought_offer' offer|mongo_id %}"><img src="{% static '/icon/offer_default.jpg' %}" class="card-img-top" alt="card text"> </a>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title"><a href="{% url 'offer' offer|mongo_id %}">{{offer.title|truncatewords_html:20|safe}}</a></h5>
                                <p class="card-text"><a href="{% url 'offer' offer|mongo_id %}">{{ offer.description|truncatewords_html:30|safe }}</a></p>
                                <p class="card-text"><a href="{% url 'offer' offer|mongo_id %}">{{ offer.city|truncatewords_html:20|safe }}</a></p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                     <form action="{% url 'export_bought_offers_to_json' %}" method="GET">
                        <button type="submit" class="px-5 btn" style="margin-top: 10px; color: rgb(191, 120, 163); border-style: solid; border-width: 0.5px; border-color: rgb(191, 120, 163);" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Export to JSON
                        </button>
                    </form>
                </div>
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>
</section>
{% endblock %}

swap/templates/edit_offer.html
{% extends 'base.html'%}
{% load static %}
{% load get_id_tag %}


{% block title %}
Add offer
{% endblock %}

{% block content %}
<section class="pb-3">
    <div class="container-fluid ">
        <div class="row ">
            <div class="col-lg-2"></div>
            <div class="col-lg-8 col-md-12">
              <form enctype="multipart/form-data" method="post">
                  {% csrf_token %}
                  <p class="fieldWrapper">
                      <label for="id_title">Название:</label>
                      <input type="text" value={{offer.title}} name="title" class="form-control" required="" id="id_title">
                  </p>
                  <p class="fieldWrapper">
                      <label for="id_description">Описание:</label>
                      <textarea name="description" cols="40" rows="10" class="form-control" required="" id="id_description">{{offer.description}}</textarea>
                  </p>
                  <p>
                        <label for="id_photo">Photo:</label>
                        <input type="file" name="photo" accept="image/*" id="id_photo">
                  </p>
                  <p class="fieldWrapper">
                        <label for="id_weight">Вес:</label>
                        <input type="number" value={{offer.weight}} name="weight" class="form-control" required="" id="id_weight">
                  </p>
                  <p class="fieldWrapper">

                        <label for="id_size">Размер:</label>
                        <input type="number" value={{offer.size}} name="size" class="form-control" required="" id="id_size">
                  </p>
                  <p class="fieldWrapper">
                            <label for="id_category">Категория:</label>
                            <select name="category" class="form-control" id="id_category">
                              <option value="Мебель">Мебель</option>

                              <option value="Одежда">Одежда</option>

                              <option value="Бытовая техника">Бытовая техника</option>

                              <option value="Посуда">Посуда</option>

                              <option value="Продукты">Продукты</option>
                            </select>
                  </p>
                  <p class="fieldWrapper">
                      <label for="id_state">Состояние:</label>
                      <select name="state" class="form-control" id="id_state">
                          <option value="Новое">Новое</option>

                          <option value="Хорошее">Хорошее</option>

                          <option value="Среднее">Среднее</option>

                          <option value="Требует ремонта">Требует ремонта</option>
                      </select>
                  </p>
                  <p class="fieldWrapper">
                        <label for="id_city">Город:</label>
                        <input type="text" value={{offer.city}} name="city" class="form-control" required="" id="id_city">
                  </p>
                  <p class="fieldWrapper">
                        <label for="id_price">Цена:</label>
                        <input type="number" value={{offer.price}} name="price" class="form-control" required="" id="id_price">
                  </p>
                  <div class="mt-3 mb-5">
                      <button type="submit" class="px-5 btn" style="color: rgb(191, 120, 163); border-style: solid; border-width: 0.5px; border-color: rgb(191, 120, 163);">Редактировать</button>
                  </div>
              </form>
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>
</section>
{% endblock %}

swap/templates/error.html
{% extends 'base.html'%}
{% load static %}

{% block title %}
Error
{% endblock %}

{% block content %}
<section class="pb-3">
    <h3 style="color: rgb(191, 120, 163); border-style: solid; border-width: 0.5px; border-color: rgb(191, 120, 163);">
    {{error_code}}
    <br>
    {{error_message}}
    </h3>
</section>
{% endblock %}

swap/templates/home.html
{% extends 'base.html'%}
{% load get_id_tag %}
{% load static %}

{% block title %}
Swap
{% endblock %}

{% block content %}
<style>
.pagination a {
  color: black;
  float: left;
  margin: auto;
  padding: 8px 16px;
  text-decoration: none;
  transition: background-color .3s;
}

.pagination a.active {
  background-color: lightcoral;
  color: white;
}
.pagination a:hover:not(.active) {background-color: rgb(223, 136, 136);}
</style>

<section class="pb-3">
    <div class="container-fluid ">
        <div class="row ">
            <div class="col-lg-2"></div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    {% for offer in page_obj %}
                    <div class="col-lg-4 col-md-6 mt-4">
                        <div class="card">
                            {% if offer.photo %}
                            <a href="{% url 'offer' offer|mongo_id %}"><img src="{{offer.photo}}" class="card-img-top" alt="card text"> </a>
                            {% else %}
                            <a href="{% url 'offer' offer|mongo_id %}"><img src="{% static '/icon/offer_default.jpg' %}" class="card-img-top" alt="card text"> </a>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title"><a href="{% url 'offer' offer|mongo_id %}">{{offer.title|truncatewords_html:20|safe}}</a></h5>
                                <p class="card-text"><a href="{% url 'offer' offer|mongo_id %}">{{ offer.description|truncatewords_html:40|safe }}</a></p>
                                <p class="card-text"><a href="{% url 'offer' offer|mongo_id %}">{{ offer.city|truncatewords_html:20|safe }}</a></p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="pagination">
                        <span class="step-links my_pag">
                            <span class="pages">
                                {% for page_number in page_obj.paginator.page_range %}
                                  {% if page_number == page_obj.number %}
                                  <a href="?page={{page_number}}" class="active">{{page_number}}</a></li>
                                  {% else %}
                                    <a href="?page={{page_number}}">{{page_number}}</a></li>
                                  {% endif %}
                                {% endfor %}
                              </span>
                        </span>
                    </div>
                    <form action="{% url 'export_offers_to_json' %}" method="GET">
                        <button type="submit" class="px-5 btn" style="margin-top: 10px; color: rgb(191, 120, 163); border-style: solid; border-width: 0.5px; border-color: rgb(191, 120, 163);" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Export to JSON
                          </button>
                    </form>
                </div>
            </div>
            
            <div class="col-lg-2"></div>
        </div>
    </div>
</section>
{% endblock %}

swap/templates/login.html
{% extends 'base.html'%}
{% load static %}

{% block title %}
Login
{% endblock %}

{% block content %}
<section class="pb-3">
    <div class="container-fluid ">
        <div class="row ">
            <div class="col-lg-2"></div>
            <div class="col-lg-8 col-md-12">
              <form enctype="multipart/form-data" method="post">
                  {% csrf_token %}
                  {{ form.non_form_errors }}
                  {{form.as_p}}
                  <div class="mt-3 mb-5">
                      <button type="submit" class="px-5 btn" style="color: rgb(191, 120, 163); border-style: solid; border-width: 0.5px; border-color: rgb(191, 120, 163);">Войти</button>
                  </div>
              </form>
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>
</section>
{% endblock %}

swap/templates/register.html
{% extends 'base.html'%}
{% load static %}

{% block title %}
Register
{% endblock %}

{% block content %}
<section class="pb-3">
    <div class="container-fluid ">
        <div class="row ">
            <div class="col-lg-2"></div>
            <div class="col-lg-8 col-md-12">
              <form enctype="multipart/form-data" method="post">
                  {% csrf_token %}
                  {{ form.non_form_errors }}
                  {{form.as_p}}
                  <div class="mt-3 mb-5">
                      <button type="submit" class="px-5 btn" style="color: rgb(191, 120, 163); border-style: solid; border-width: 0.5px; border-color: rgb(191, 120, 163);">Зарегестрироваться</button>
                  </div>
              </form>
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>
</section>
{% endblock %}